### ISSUE TITLE
error when running - ImportError: cannot import name 'cli'

### ISSUE THREAD

**Issue by rickchong** [amarder/iterdata#58]
Hi, I'm trying to learn how to datapipe... however, I bumped onto the following error. I think I have installed all the dependencies. 

```
C:\python>datapipe
Traceback (most recent call last):
  File "C:\Python\Scripts\datapipe-script.py", line 11, in <module>
    load_entry_point('iterdata==0.1', 'console_scripts', 'datapipe')()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python\lib\site-packages\iterdata\__main__.py", line 1, in <module>
    from cli import cli
ImportError: cannot import name 'cli'
```

**Comment by amarder** [comment]
What version of Python are you using? I've only tested iterdata on Python version 2.7. Additionally, I have not tested the package on Windows.

Best, Andrew

**Comment by rickchong** [comment]
Hey Andrew, yea just realized that there is compatibility issue with Windows. I looked at your methodology and did something similar using R. Thanks!
